// Auto-generated by scripts/gen-releases.mjs — DO NOT EDIT
// Run: node scripts/gen-releases.mjs

export interface ReleaseHighlight {
  kind: "feat" | "fix" | "security";
  text: string;
}

export interface Release {
  version: string;
  date: string;
  highlights: ReleaseHighlight[];
}

export const RELEASES: Release[] = [
  {
    "version": "1.3.0",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "shared memory system — SQLite-backed memory store with 6 MCP tools (memory_write/read/search/list/delete/stats)"
      },
      {
        "kind": "feat",
        "text": "swarm coordination — 6 MCP tools for multi-agent orchestration (status/broadcast/assign_task/worker_health/respawn/set_topology)"
      },
      {
        "kind": "feat",
        "text": "learned patterns — 4 MCP tools for saving and querying learned patterns"
      },
      {
        "kind": "feat",
        "text": "hooks system — lifecycle event emitters (pane_spawned/exited/idle) with 3 MCP tools (hooks_status/log/fire)"
      },
      {
        "kind": "feat",
        "text": "trajectory tracking — action sequence recording with auto-pattern extraction, 8 MCP tools"
      },
      {
        "kind": "feat",
        "text": "file access tools — file_read/write/search for structured agent file access"
      },
      {
        "kind": "feat",
        "text": "system diagnostics — system_info/diagnostics MCP tools"
      },
      {
        "kind": "feat",
        "text": "worker trigger detection — 7 regex triggers (optimize/audit/document/refactor/benchmark/testgaps/deepdive)"
      },
      {
        "kind": "feat",
        "text": "provider health tracking — success/error counts per provider with provider_health tool"
      },
      {
        "kind": "feat",
        "text": "memory UI panel — visual sidebar with Memories/Patterns tabs, search and filters"
      },
      {
        "kind": "feat",
        "text": "shared memory protocol — all agents share memory in same workspace and auto-adapt to changes"
      },
      {
        "kind": "feat",
        "text": "squad persistence — save/load/delete squad configurations (JSON-file-backed)"
      },
      {
        "kind": "feat",
        "text": "MCP tools expanded from 37 to 86 total (+49 new tools)"
      },
      {
        "kind": "fix",
        "text": "git restriction — all agents prohibited from git add/commit/push without explicit user request"
      }
    ]
  },
  {
    "version": "1.2.25",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "copy and paste buttons in context menu"
      },
      {
        "kind": "feat",
        "text": "add clipboard read functionality and improve context menu handling in TerminalPane"
      },
      {
        "kind": "feat",
        "text": "dropdown terminal fixed"
      },
      {
        "kind": "feat",
        "text": "Quick Actions white theme OK"
      },
      {
        "kind": "feat",
        "text": "size button close terminal 20"
      },
      {
        "kind": "feat",
        "text": "add context menu, quick actions, and fix selection visibility"
      }
    ]
  },
  {
    "version": "1.2.24",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "orchestrator spawns duplicate workers instead of reusing idle ones (v1.2.24)"
      }
    ]
  },
  {
    "version": "1.2.23",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pane_write large text submit + cursor-pointer on all clickable elements (v1.2.23)"
      },
      {
        "kind": "fix",
        "text": "pane_write Enter not submitting in readline paste-mode (v1.2.22)"
      }
    ]
  },
  {
    "version": "1.2.20",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "MIMO 401 — masked secrets from frontend overwriting real API key on spawn"
      }
    ]
  },
  {
    "version": "1.2.19",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "squad spawner passes role + env to inject correct prompts"
      }
    ]
  },
  {
    "version": "1.2.18",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "auto-inject role-specific prompts on pane spawn"
      }
    ]
  },
  {
    "version": "1.2.17",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "echo suppression for MCP inter-agent communication"
      },
      {
        "kind": "fix",
        "text": "use notifyPane instead of writePane for inter-agent messages to avoid bypassing permissions issue"
      }
    ]
  },
  {
    "version": "1.2.16",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pane_spawn model-based provider resolution using enhanced model map"
      }
    ]
  },
  {
    "version": "1.2.15",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "restore MIMO regional routes, mimo-compat provider handling, and fullPage screenshot"
      },
      {
        "kind": "fix",
        "text": "MIMO 404 error, provider env var mapping, and pane_write submit reliability"
      }
    ]
  },
  {
    "version": "1.2.22",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pane_write Enter not submitting in readline paste-mode (v1.2.22)"
      }
    ]
  },
  {
    "version": "1.2.21",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "MIMO 401 — masked secrets from frontend overwriting real API key on spawn"
      },
      {
        "kind": "feat",
        "text": "squad spawner passes role + env to inject correct prompts"
      },
      {
        "kind": "feat",
        "text": "auto-inject role-specific prompts on pane spawn"
      },
      {
        "kind": "feat",
        "text": "echo suppression for MCP inter-agent communication"
      },
      {
        "kind": "fix",
        "text": "use notifyPane instead of writePane for inter-agent messages to avoid bypassing permissions issue"
      },
      {
        "kind": "fix",
        "text": "pane_spawn model-based provider resolution using enhanced model map"
      },
      {
        "kind": "fix",
        "text": "restore MIMO regional routes, mimo-compat provider handling, and fullPage screenshot"
      },
      {
        "kind": "fix",
        "text": "MIMO 404 error, provider env var mapping, and pane_write submit reliability"
      },
      {
        "kind": "fix",
        "text": "auto-update feedback e reinício automático"
      }
    ]
  },
  {
    "version": "1.2.13",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "export buildEdges function and import it in SessionMap"
      },
      {
        "kind": "fix",
        "text": "guard webContents.send against destroyed window on close; fix npm install path-with-spaces on Windows"
      },
      {
        "kind": "fix",
        "text": "fix openclaude install on linux and windows with npm check and timeout"
      },
      {
        "kind": "fix",
        "text": "repair missing Windows registry keys to fix auto-update error"
      },
      {
        "kind": "feat",
        "text": "implement PtyManager for cross-platform process management and terminal session handling"
      },
      {
        "kind": "fix",
        "text": "fix provider banner and system prompt flag for openclaude v0.10"
      },
      {
        "kind": "fix",
        "text": "remove generic openai fallback provider argument that forced codex model on custom providers"
      },
      {
        "kind": "fix",
        "text": "pass anthropic as provider arg for mimo-compat/anthropic-compat to override codex default"
      },
      {
        "kind": "fix",
        "text": "pass --provider arg for openclaude v0.10+ compatibility"
      },
      {
        "kind": "feat",
        "text": "add MIT License to the project"
      },
      {
        "kind": "fix",
        "text": "guard against empty RELEASES array causing black screen"
      }
    ]
  }
];
