// Auto-generated by scripts/gen-releases.mjs — DO NOT EDIT
// Run: node scripts/gen-releases.mjs

export interface ReleaseHighlight {
  kind: "feat" | "fix" | "security";
  text: string;
}

export interface Release {
  version: string;
  date: string;
  highlights: ReleaseHighlight[];
}

export const RELEASES: Release[] = [
  {
    "version": "1.2.9",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "fix banner showing Codex for Gemini/Mimo providers in openclaude v0.10"
      },
      {
        "kind": "fix",
        "text": "use --append-system-prompt-file to avoid Windows CLI argument length limits"
      }
    ]
  },
  {
    "version": "1.2.8",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pass anthropic as provider arg for mimo-compat/anthropic-compat to override codex default"
      },
      {
        "kind": "fix",
        "text": "pass --provider arg for openclaude v0.10+ compatibility"
      },
      {
        "kind": "feat",
        "text": "add MIT License to the project"
      },
      {
        "kind": "fix",
        "text": "guard against empty RELEASES array causing black screen"
      }
    ]
  },
  {
    "version": "1.2.7",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pass anthropic as provider arg for mimo-compat/anthropic-compat to override codex default"
      }
    ]
  },
  {
    "version": "1.2.6",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pass --provider arg for openclaude v0.10+ compatibility"
      }
    ]
  },
];
