// Auto-generated by scripts/gen-releases.mjs — DO NOT EDIT
// Run: node scripts/gen-releases.mjs

export interface ReleaseHighlight {
  kind: "feat" | "fix" | "security";
  text: string;
}

export interface Release {
  version: string;
  date: string;
  highlights: ReleaseHighlight[];
}

export const RELEASES: Release[] = [
  {
    "version": "1.4.0",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "cost per task tracking, PTY token parser, per-task UI, hooks expansion, consensus algorithms"
      }
    ]
  },
  {
    "version": "1.3.8",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "automatic shared memory — agents auto-notify peers on file/memory changes"
      }
    ]
  },
  {
    "version": "1.3.7",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "MCP token optimization, smart HTML scraping, full-page screenshot, browser workspace resolution"
      }
    ]
  },
  {
    "version": "1.3.5",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "add 4-level fallback for stdio path resolution + chain bundle:stdio in build"
      },
      {
        "kind": "fix",
        "text": "MCP stdio server works outside Electron asar after install"
      }
    ]
  },
  {
    "version": "1.3.4",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "auto-setup Claude Code integration on startup + bump version to 1.3.4"
      },
      {
        "kind": "fix",
        "text": "update release date for version 1.3.3"
      }
    ]
  },
  {
    "version": "1.3.3",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "add stdio MCP server for CLI mode + fix statusline model parsing"
      }
    ]
  },
  {
    "version": "1.3.2",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "add Codebrain statusline for Claude Code + bump version to 1.3.2"
      },
      {
        "kind": "fix",
        "text": "context menu position accounting for CSS zoom"
      },
      {
        "kind": "feat",
        "text": "add comprehensive .claude/ directory for Claude Code integration"
      },
      {
        "kind": "feat",
        "text": "add skill repository system with 5 MCP tools and SkillsPanel UI"
      }
    ]
  },
  {
    "version": "1.3.1",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "semantic version sorting in gen-releases script and regenerate releases data"
      },
      {
        "kind": "feat",
        "text": "add memory/pattern detail modals, rich prompt patterns, and update docs to 86 MCP tools"
      }
    ]
  },
  {
    "version": "1.3.0",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "add hooks system, trajectory tracking, and squad persistence — v1.3.0"
      },
      {
        "kind": "feat",
        "text": "add shared memory protocol and git restriction to all agent prompts"
      },
      {
        "kind": "feat",
        "text": "add shared memory, swarm coordination, and 38 new MCP tools"
      }
    ]
  },
  {
    "version": "1.2.25",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "copy and paste buttons in context menu"
      },
      {
        "kind": "feat",
        "text": "add clipboard read functionality and improve context menu handling in TerminalPane"
      },
      {
        "kind": "feat",
        "text": "dropdown terminal fixed"
      },
      {
        "kind": "feat",
        "text": "Quick Actions white theme OK"
      },
      {
        "kind": "feat",
        "text": "size button close terminal 20"
      },
      {
        "kind": "feat",
        "text": "add context menu, quick actions, and fix selection visibility"
      }
    ]
  },
  {
    "version": "1.2.24",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "orchestrator spawns duplicate workers instead of reusing idle ones (v1.2.24)"
      }
    ]
  },
  {
    "version": "1.2.23",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pane_write large text submit + cursor-pointer on all clickable elements (v1.2.23)"
      }
    ]
  },
  {
    "version": "1.2.22",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pane_write Enter not submitting in readline paste-mode (v1.2.22)"
      }
    ]
  },
  {
    "version": "1.2.20",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "MIMO 401 — masked secrets from frontend overwriting real API key on spawn"
      }
    ]
  },
  {
    "version": "1.2.19",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "squad spawner passes role + env to inject correct prompts"
      }
    ]
  },
  {
    "version": "1.2.18",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "auto-inject role-specific prompts on pane spawn"
      }
    ]
  },
  {
    "version": "1.2.17",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "echo suppression for MCP inter-agent communication"
      },
      {
        "kind": "fix",
        "text": "use notifyPane instead of writePane for inter-agent messages to avoid bypassing permissions issue"
      }
    ]
  },
  {
    "version": "1.2.16",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "pane_spawn model-based provider resolution using enhanced model map"
      }
    ]
  },
  {
    "version": "1.2.15",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "restore MIMO regional routes, mimo-compat provider handling, and fullPage screenshot"
      },
      {
        "kind": "fix",
        "text": "MIMO 404 error, provider env var mapping, and pane_write submit reliability"
      }
    ]
  },
  {
    "version": "1.2.14",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "fix",
        "text": "auto-update feedback e reinício automático"
      }
    ]
  },
  {
    "version": "1.2.13",
    "date": "maio 2026",
    "highlights": [
      {
        "kind": "feat",
        "text": "export buildEdges function and import it in SessionMap"
      },
      {
        "kind": "fix",
        "text": "guard webContents.send against destroyed window on close; fix npm install path-with-spaces on Windows"
      },
      {
        "kind": "fix",
        "text": "fix openclaude install on linux and windows with npm check and timeout"
      },
      {
        "kind": "fix",
        "text": "repair missing Windows registry keys to fix auto-update error"
      },
      {
        "kind": "feat",
        "text": "implement PtyManager for cross-platform process management and terminal session handling"
      },
      {
        "kind": "fix",
        "text": "fix provider banner and system prompt flag for openclaude v0.10"
      },
      {
        "kind": "fix",
        "text": "remove generic openai fallback provider argument that forced codex model on custom providers"
      },
      {
        "kind": "fix",
        "text": "pass anthropic as provider arg for mimo-compat/anthropic-compat to override codex default"
      },
      {
        "kind": "fix",
        "text": "pass --provider arg for openclaude v0.10+ compatibility"
      },
      {
        "kind": "feat",
        "text": "add MIT License to the project"
      },
      {
        "kind": "fix",
        "text": "guard against empty RELEASES array causing black screen"
      }
    ]
  }
];
